# Generated by Django 4.1.6 on 2023-02-23 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.membership'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 14, 6, 32, 34430, tzinfo=datetime.timezone.utc)),
        ),
    ]
